[package]
name = "fuzz"
version = "0.0.0"
publish = false
edition.workspace = true
rust-version.workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
rasn-compiler = { path = "../rasn-compiler/" }

[[bin]]
name = "compile"
path = "fuzz_targets/compile.rs"
test = false
doc = false
bench = false
